spring.application.name=erp-backend
server.port=8080
front.end.host=http://localhost:5173
######## 1. 資料庫基本連線 (SQL Server) ##########
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=iSpan_Project;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=000000

######## 2. JPA / Hibernate 自動建表 ##########
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

######## 3. 檔案上傳限制與進階設定 ##########
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=80MB
spring.mvc.hiddenmethod.filter.enabled=true
######## 4. 控制台彩色日誌顯示 ##########
spring.output.ansi.enabled=always